In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
import os
import pathlib
import random
import glob
import matplotlib.pyplot as plt
from skimage.transform import resize
from numpy.random import randn
from matplotlib.image import imread
from keras.preprocessing import image
from PIL import Image
import os, glob
import numpy as np
from sklearn.model_selection import train_test_split

C:\Users\ICT01_05\Anaconda3\envs\tf_test\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\ICT01_05\Anaconda3\envs\tf_test\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\ICT01_05\Anaconda3\envs\tf_test\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\ICT01_05\Anaconda3\envs\tf_test\lib\site-packages

In [2]:
img_dir = "C:/Users/ICT01_05/Desktop/3차/images"
img_dir = pathlib.Path(img_dir)

In [3]:
label_names={'product' : 0, 'potg' : 1}
label_key=['product', 'potg']

In [4]:
all_img = list(img_dir.glob('*/*.jpg'))
all_img = [str(path) for path in all_img]
random.shuffle(all_img)
all_labels=[label_names[pathlib.Path(path).parent.name] for path in all_img]

In [11]:
x=[]
y=[]
for i,f in enumerate(all_img) :
    img = Image.open(f)
    img = img.convert("RGB")
#     img = img.resize((image_w, image_h))
    data = np.asarray(img)
    x.append(data)
    y.append(all_labels)
    if i % 10 == 0:
        print(i, '\n', data)
        
x = np.array(x)
y = np.array(y)
x

0 
 [[[189 194 190]
  [188 193 189]
  [188 193 189]
  ...
  [203 207 206]
  [203 207 206]
  [200 204 203]]

 [[189 194 190]
  [188 193 189]
  [188 193 189]
  ...
  [200 204 203]
  [202 206 205]
  [202 206 205]]

 [[188 193 189]
  [188 193 189]
  [188 193 189]
  ...
  [200 204 203]
  [201 205 204]
  [202 206 205]]

 ...

 [[161 165 166]
  [163 167 168]
  [163 167 168]
  ...
  [206 209 214]
  [206 209 214]
  [207 210 215]]

 [[163 167 168]
  [162 166 167]
  [164 168 169]
  ...
  [207 210 215]
  [206 209 214]
  [207 210 215]]

 [[165 169 170]
  [163 167 168]
  [165 169 170]
  ...
  [207 210 215]
  [206 209 214]
  [207 210 215]]]
10 
 [[[222 220 208]
  [220 218 206]
  [219 217 205]
  ...
  [219 215 204]
  [227 223 212]
  [235 231 220]]

 [[220 218 206]
  [220 218 206]
  [220 218 206]
  ...
  [224 220 209]
  [228 224 213]
  [230 226 215]]

 [[219 217 205]
  [221 219 207]
  [221 219 207]
  ...
  [224 220 209]
  [226 222 211]
  [224 220 209]]

 ...

 [[179 178 158]
  [179 178 158]
  [180 179 

130 
 [[[130 112 100]
  [135 117 105]
  [126 108  96]
  ...
  [203 205 204]
  [204 206 205]
  [205 207 206]]

 [[128 110  98]
  [133 115 103]
  [128 110  98]
  ...
  [203 205 204]
  [203 205 204]
  [204 206 205]]

 [[126 108  96]
  [129 111  99]
  [128 110  98]
  ...
  [202 204 203]
  [202 204 203]
  [203 205 204]]

 ...

 [[ 56  37  23]
  [ 59  40  26]
  [ 59  40  26]
  ...
  [167 169 168]
  [166 168 167]
  [167 169 168]]

 [[ 57  38  24]
  [ 60  41  27]
  [ 59  40  26]
  ...
  [167 169 168]
  [166 168 167]
  [166 168 167]]

 [[ 59  40  26]
  [ 60  41  27]
  [ 57  38  24]
  ...
  [167 169 168]
  [166 168 167]
  [166 168 167]]]
140 
 [[[201 197 185]
  [198 194 182]
  [200 196 184]
  ...
  [225 220 214]
  [225 220 214]
  [226 221 215]]

 [[201 197 185]
  [200 196 184]
  [202 198 186]
  ...
  [226 221 215]
  [226 221 215]
  [226 221 215]]

 [[200 196 184]
  [200 196 184]
  [201 197 185]
  ...
  [225 220 214]
  [225 220 214]
  [225 220 214]]

 ...

 [[185 183 171]
  [185 183 171]
  [185 1

260 
 [[[211 215 214]
  [212 216 215]
  [211 215 214]
  ...
  [199 198 193]
  [181 180 175]
  [159 158 153]]

 [[211 215 214]
  [213 217 216]
  [213 217 216]
  ...
  [195 194 189]
  [187 186 181]
  [175 174 169]]

 [[210 214 213]
  [212 216 215]
  [213 217 216]
  ...
  [189 188 183]
  [193 192 187]
  [193 192 187]]

 ...

 [[147 152 146]
  [147 152 146]
  [148 153 147]
  ...
  [182 182 180]
  [182 182 180]
  [182 182 180]]

 [[150 155 149]
  [148 153 147]
  [148 153 147]
  ...
  [180 180 178]
  [182 182 180]
  [182 182 180]]

 [[154 159 153]
  [149 154 148]
  [148 153 147]
  ...
  [183 183 181]
  [184 184 182]
  [184 184 182]]]
270 
 [[[190 192 187]
  [189 191 186]
  [189 191 186]
  ...
  [220 220 222]
  [223 223 225]
  [220 220 222]]

 [[189 191 186]
  [190 192 187]
  [190 192 187]
  ...
  [220 220 222]
  [222 222 224]
  [220 220 222]]

 [[189 191 186]
  [190 192 187]
  [190 192 187]
  ...
  [220 220 222]
  [221 221 223]
  [220 220 222]]

 ...

 [[173 177 176]
  [174 178 177]
  [175 1

390 
 [[[188 188 186]
  [188 188 186]
  [189 189 187]
  ...
  [216 214 215]
  [216 214 215]
  [212 210 211]]

 [[188 188 186]
  [189 189 187]
  [189 189 187]
  ...
  [217 215 216]
  [217 215 216]
  [214 212 213]]

 [[188 188 186]
  [190 190 188]
  [189 189 187]
  ...
  [215 213 214]
  [215 213 214]
  [213 211 212]]

 ...

 [[167 169 166]
  [167 169 166]
  [167 169 166]
  ...
  [208 208 210]
  [208 208 210]
  [209 209 211]]

 [[168 170 167]
  [167 169 166]
  [167 169 166]
  ...
  [208 208 210]
  [208 208 210]
  [208 208 210]]

 [[166 168 165]
  [166 168 165]
  [166 168 165]
  ...
  [208 208 210]
  [208 208 210]
  [207 207 209]]]
400 
 [[[218 218 206]
  [213 213 201]
  [216 216 204]
  ...
  [224 221 206]
  [224 221 206]
  [221 218 203]]

 [[220 220 208]
  [218 218 206]
  [220 220 208]
  ...
  [220 217 202]
  [221 218 203]
  [220 217 202]]

 [[218 218 206]
  [221 221 209]
  [223 223 211]
  ...
  [220 217 202]
  [220 217 202]
  [220 217 202]]

 ...

 [[167 161 147]
  [167 161 147]
  [170 1

array([[[[189, 194, 190],
         [188, 193, 189],
         [188, 193, 189],
         ...,
         [203, 207, 206],
         [203, 207, 206],
         [200, 204, 203]],

        [[189, 194, 190],
         [188, 193, 189],
         [188, 193, 189],
         ...,
         [200, 204, 203],
         [202, 206, 205],
         [202, 206, 205]],

        [[188, 193, 189],
         [188, 193, 189],
         [188, 193, 189],
         ...,
         [200, 204, 203],
         [201, 205, 204],
         [202, 206, 205]],

        ...,

        [[161, 165, 166],
         [163, 167, 168],
         [163, 167, 168],
         ...,
         [206, 209, 214],
         [206, 209, 214],
         [207, 210, 215]],

        [[163, 167, 168],
         [162, 166, 167],
         [164, 168, 169],
         ...,
         [207, 210, 215],
         [206, 209, 214],
         [207, 210, 215]],

        [[165, 169, 170],
         [163, 167, 168],
         [165, 169, 170],
         ...,
         [207, 210, 215],
        

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train = x_train.astype("float64")/256
# x_test = x_test.astype("float")/256
x_train

MemoryError: Unable to allocate 10.5 GiB for an array with shape (309, 3024, 4032, 3) and data type uint8

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)