In [1]:
# flask 
import flask #웹서버 기능 5000번 포트로 서비스

In [2]:
import matplotlib # 시각화 패키지
import numpy as np # 별칭 class
print(np.__version__) # 상위 오브젝트가 가진 속성
def pprint(arr): # ndarray: numpy의 기본 데이터 배열
    print("type:{}".format(type(arr)))
    print("shape:{}, dimension:{},dtype:{}".format(arr.shape,arr.ndim,arr.dtype))
    print("Array's Data: \n",arr)
    # 숫자의 디폴트는 int32
arr = [1.0,2.0,3.0] # 리스트
a = np.array([1,2,3]) # ndarray 생성함수 (매개변수:리스트)
pprint(a)

1.16.5
type:<class 'numpy.ndarray'>
shape:(3,), dimension:1,dtype:int32
Array's Data: 
 [1 2 3]


In [3]:
# 인스턴스상태
a = np.array([0,1,2,3,4,5,6,7,8,9]) # ndarry
print(id(a)) # pythone core 주소값 확인
print(a.size) # 데이터 개수
print(a.astype(np.float32)) # 데이터 타입 변경, numpy는 행중심, 동질적
print(a.dtype.itemsize*a.size) # 전체 메모리 사이즈(바이트)
# literator for in range => list
a = np.arange(1000)  # => ndarry
a

1902539497184
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
40


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [4]:
# ndarray 초기화 함수들
print(np.zeros((3,4)))
print(np.ones((2,3,4), dtype = np.int16)) # 1, 3차원 (면, 행, 열)
print(np.full((2,2),7))
print(np.eye(4)) # 대각행렬 identity 행렬연산에서 항등원 + : 0/ * : 1 / 행렬 : 대각행렬
print(np.empty((4,2))) # 쓰레기값

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.57306049e-321]
 [1.06811015e-306 1.24611470e-306]]


In [9]:
a = np.arange(0,100,10) # 0부터 10씩 증가해서 100 직전까지, ndarray
indices = [1,5,-1] # 리스트
print(indices)
b = a[indices] # 리스트를 첨자로 사용
print(a)
print(b)

[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]


In [15]:
#a = np.arange(11,35) 개수가 맞아야함 
a = np.arange(11,36) # 1차원
a.shape = (5,5) # 행렬 모양, 정상모양을 갖춘 개수
print(a)
print(type(a))
print(a.dtype)
print(a.size) # 개수 25개
print(a.shape) # 차수 (5,5)
print(a.ndim) # 2차원
print(a.nbytes) # 100바이트 = 25 * 4
print(a.strides) #  (20,4) 4는 다음 열의 데이터는 몇바이트를 건너뛰어야 하는가
                 # 다음 행은 몇바이트를 건너뛰어야 하는가 20은 한행에 5개이므로 5*4

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
<class 'numpy.ndarray'>
int32
25
(5, 5)
2
100
(20, 4)


In [16]:
arr = np.arange(10)
print(type(arr))
print(arr)
print(arr[5])
print(arr[5:8]) # 마지막 불포함
arr[5:8] = 12   # 데이터 업데이트
print(arr[1:6])

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 1  2  3  4 12]


In [18]:
# numpy 첨자 생략 불가 [,4]
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d[0]) # 행우선
print(arr2d[0][2])
print(arr2d[0,2])
print(arr2d[:2]) #0,1행
print(arr2d[:2,1:]) # 끝까지
print(arr2d[:,1:]) # 모든행
print(arr2d[1,:2])
print(arr2d[2, :1])
arr2d[:2, :1]=0
arr2d[:2, :1] =0
print(arr2d)

[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]
 [8 9]]
[4 5]
[7]
[[0 2 3]
 [0 5 6]
 [7 8 9]]


In [20]:
# 실제 저장은 일렬로 사람이 데이터를 다루는 것은 입체로 480바이트
# 행렬연산에서 앞의 행렬열수와 뒤의 행렬의 행수를 일치 시켜야 행렬곱이 가능
# 행렬곱에서 행렬 앞뒤로 바꾸면 안됨
print("스트라이크의 값", np.ones((3,4,5), dtype = np.float64). strides) # 3면 4행 5열
# (160, 40, 8) float64는 8바이트, 다음면 이동하기위해서 20*8 , 다음행 : 5*8, 다음 열 : 8

스트라이크의 값 (160, 40, 8)


In [47]:
# 문제
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 면이 2개 , 행2개 열 3개
print("첫 차원", arr3d[0])
print("첫차원 첫행은 = ", arr3d[0][0])
print("첫 요소는 = ", arr3d[0][0][0])
print(" 8출력 ", arr3d[1][0][1])
print(" 12출력 ", arr3d[1][1][2]) # 인덱스

첫 차원 [[1 2 3]
 [4 5 6]]
첫차원 첫행은 =  [1 2 3]
첫 요소는 =  1
 8출력  8
 12출력  12


In [49]:
# 백업이 안됨 : 대입하면 같은 주소를 가리키기 때문에
old_values = arr3d # 대입 : 주소를 복사
arr3d[0] = 42
print("값의 변경후")
print(arr3d)
print("이전 값으로 복구")
arr3d = old_values
print(arr3d)

값의 변경후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [50]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
old_values = arr3d.copy()
arr3d[0] = 42
print("값의 변경후")
print(arr3d)
print("이전 값으로 복구")
arr3d = old_values
print(arr3d)


값의 변경후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [53]:
z = np.arange(36)
print(z)
z = z.reshape((6, 6))
print(z)

reshape2 = z.reshape((2,3,6))
print(reshape2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [56]:
arr = np.arange(32).reshape((8, 4))
print(arr)
print(arr[[1,5,7,2]])# 행중심
print(arr[[-1,-5,-7,-2]]) # 거꾸로 인덱싱
print(arr[[1, 5, 7, 2],[0, 3, 1, 2]])
# fancy 인덱싱 
print(arr[[1, 5, 7, 2]][:,[0, 1, 2, 3]])
print(arr[[1, 5, 7, 2]][:,[0, 3, 1, 2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]
[ 4 23 29 10]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [81]:
arr = []
for i in range(6) :
    ad=[]
    for j in range(6) :
        ad.append(i*10+j)
    arr.append(ad)
#print(arr)
arr = np.array(arr)
print("빨간색",arr[[0,2,5],2])
print("주황색", arr[[0,1,2,3,4],[1,2,3,4,5]]) 
print("하늘색", arr[3:6][:,[0,2,5]])


빨간색 [ 2 22 52]
주황색 [ 1 12 23 34 45]
하늘색 [[30 32 35]
 [40 42 45]
 [50 52 55]]


In [108]:
print("빨간색", arr[:,2])
print("주황색", arr[0,[3,4]])
print("녹색", arr[[2,4]][:,[0,2,4]])
print("하늘색", arr[4:][:,[4,5]])


빨간색 [ 2 12 22 32 42 52]
주황색 [3 4]
녹색 [[20 22 24]
 [40 42 44]]
하늘색 [[44 45]
 [54 55]]


In [112]:
x = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]]) # 4x3
v = np.array([1,0,1])
print("타일출력")
vv = np.tile(v, (4,1))
print(vv)
y = x + vv # 4x3 배열연산 -> 요소별 연산
print(y)
# 배열 연산 : 양쪽 차원이 일치해야함, 한쪽차원은 맞아야함 4x3, 1x3 (0), 4x3 1x4 (x)
print(x+v) # 4x3, 1x3 broadcasting
print(x+3)

타일출력
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [118]:
x = np.arange(6).reshape((3,2))
print(x)
# 거듭제곱(행열곱)
# x@x # 앞의 행렬 열수와 뒤의 행렬의 행수가 일치해야함
# 전치행렬
print(x@x.T)
print(np.transpose(x))

[[0 1]
 [2 3]
 [4 5]]
[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 41]]
[[0 2 4]
 [1 3 5]]


In [120]:
arr = np.arange(24).reshape((2,3,4)) # 2면 3행 4열 인덱스는 0,1,2
print(arr)
print(arr.transpose((1,0,2))) #  인덱스, 면하고 행 바꾸기 3,2,4
print(arr.transpose((0,2,1))) # 2,4,3

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [124]:
# Boolean indexing (True/False)
# 문자열은 대소문자 구분
names = np.array(['Seoul', 'Daejun', 'chungju', 'seoul', 'chungju', 'Daejun', 'Daejun'])
data = np.random.randn(7, 4) # 정규분포에서 출력
print(names == 'Seoul') # 1,0,0,0,0,0,0
print(data) 
print(type(data))
print(data[names == 'Seoul']) # 0번행 #1,0,0,0,0,0,0
print(data[names == 'Seoul', 2:])
print(data[names == 'Seoul', 3])
print(names != 'Seoul')
print(~(names == 'Seoul'))
mask = (names == 'Seoul') | (names == 'chungju')
print(mask)
print(data[mask])


[ True False False False False False False]
[[ 0.19169334 -1.49398506 -1.18293848  1.53786757]
 [ 0.7268516  -0.79878769  0.23663762 -1.22652008]
 [-0.3388016   0.14826502  1.08721933 -0.1618077 ]
 [-1.66016085  1.00603113 -0.7088728   0.28716659]
 [-1.05357916 -0.01466582  1.07920419  0.52029141]
 [-0.21177772  0.39917727  1.53531685 -0.6106963 ]
 [-1.09742486 -0.46818719 -1.15226686 -0.46544451]]
<class 'numpy.ndarray'>
[[ 0.19169334 -1.49398506 -1.18293848  1.53786757]]
[[-1.18293848  1.53786757]]
[1.53786757]
[False  True  True  True  True  True  True]
[False  True  True  True  True  True  True]
[ True False  True False  True False False]
[[ 0.19169334 -1.49398506 -1.18293848  1.53786757]
 [-0.3388016   0.14826502  1.08721933 -0.1618077 ]
 [-1.05357916 -0.01466582  1.07920419  0.52029141]]


In [125]:
print(data[names == 'Seoul'])

[[ 0.19169334 -1.49398506 -1.18293848  1.53786757]]


In [126]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
print(zip(xarr, yarr, cond)) # zip : 요소별로 데이터 묶기, 고유포맷
print(list(zip(xarr, yarr, cond)))
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)] # 3항연산자
print("result = ", result) 

[(1.1, 2.1, True), (1.2, 2.2, False), (1.3, 2.3, True), (1.4, 2.4, True), (1.5, 2.5, False)]
result =  [1.1, 2.2, 1.3, 1.4, 2.5]


In [128]:
result = np.where(cond, xarr, yarr)
print(result)

arr = np.random.randn(4,4)
print(arr)
print(np.where(arr>0, 2,-2))

[1.1 2.2 1.3 1.4 2.5]
[[ 0.41576616  0.41813592  1.54280933 -0.44418781]
 [-1.93263153 -0.18486574  0.4064897   1.1000093 ]
 [-1.81539618 -0.68226457  0.46732827  0.51891497]
 [-1.13280894 -2.42409122 -0.03594971 -0.52312031]]
[[ 2  2  2 -2]
 [-2 -2  2  2]
 [-2 -2  2  2]
 [-2 -2 -2 -2]]


In [ ]:
문제 다음 데이터를 이용하여 두개 다 참일 때는 0, cond1이 참일 때는 1, cond2가 참일때는 2 그외일 때는 3으로 처리하여 출력

In [150]:
result = []
cond1 = np.array([1,0,1,1,0,0,1], dtype = bool)
cond2 = np.array([0,1,1,1,0,1,1], dtype = bool)
print(cond1); print(cond2)

[ True False  True  True False False  True]
[False  True  True  True False  True  True]


In [151]:
for i in range(len(cond1)):
    if(cond1[i] and cond2[i]) :
        result.append(0)
    elif cond1[i] :
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else :
        result.append(3)
print("조건문",result)

조건문 [1, 2, 0, 0, 3, 2, 0]


In [154]:
result = np.where(cond1&cond2, 0, np.where(cond1, 1, np.where(cond2,2,3)))
print("3항 연산자",result)

3항 연산자 [1 2 0 0 3 2 0]


In [155]:
result = 1*(cond1& ~cond2) + 2*(cond2 & ~cond1) + 3 *~(cond1|cond2)
print("수식을 이용한", result)

수식을 이용한 [1 2 0 0 3 2 0]


In [157]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)
z = np.zeros_like(x) # 다른 행렬과 같은 사이즈로 초기화

for i in range(10000) :
    z[i] = x[i] + y[i]
    print(z[i])

10002
10004
10006
10008
10010
10012
10014
10016
10018
10020
10022
10024
10026
10028
10030
10032
10034
10036
10038
10040
10042
10044
10046
10048
10050
10052
10054
10056
10058
10060
10062
10064
10066
10068
10070
10072
10074
10076
10078
10080
10082
10084
10086
10088
10090
10092
10094
10096
10098
10100
10102
10104
10106
10108
10110
10112
10114
10116
10118
10120
10122
10124
10126
10128
10130
10132
10134
10136
10138
10140
10142
10144
10146
10148
10150
10152
10154
10156
10158
10160
10162
10164
10166
10168
10170
10172
10174
10176
10178
10180
10182
10184
10186
10188
10190
10192
10194
10196
10198
10200
10202
10204
10206
10208
10210
10212
10214
10216
10218
10220
10222
10224
10226
10228
10230
10232
10234
10236
10238
10240
10242
10244
10246
10248
10250
10252
10254
10256
10258
10260
10262
10264
10266
10268
10270
10272
10274
10276
10278
10280
10282
10284
10286
10288
10290
10292
10294
10296
10298
10300
10302
10304
10306
10308
10310
10312
10314
10316
10318
10320
10322
10324
10326
10328
10330
10332
1033

14182
14184
14186
14188
14190
14192
14194
14196
14198
14200
14202
14204
14206
14208
14210
14212
14214
14216
14218
14220
14222
14224
14226
14228
14230
14232
14234
14236
14238
14240
14242
14244
14246
14248
14250
14252
14254
14256
14258
14260
14262
14264
14266
14268
14270
14272
14274
14276
14278
14280
14282
14284
14286
14288
14290
14292
14294
14296
14298
14300
14302
14304
14306
14308
14310
14312
14314
14316
14318
14320
14322
14324
14326
14328
14330
14332
14334
14336
14338
14340
14342
14344
14346
14348
14350
14352
14354
14356
14358
14360
14362
14364
14366
14368
14370
14372
14374
14376
14378
14380
14382
14384
14386
14388
14390
14392
14394
14396
14398
14400
14402
14404
14406
14408
14410
14412
14414
14416
14418
14420
14422
14424
14426
14428
14430
14432
14434
14436
14438
14440
14442
14444
14446
14448
14450
14452
14454
14456
14458
14460
14462
14464
14466
14468
14470
14472
14474
14476
14478
14480
14482
14484
14486
14488
14490
14492
14494
14496
14498
14500
14502
14504
14506
14508
14510
14512
1451

17554
17556
17558
17560
17562
17564
17566
17568
17570
17572
17574
17576
17578
17580
17582
17584
17586
17588
17590
17592
17594
17596
17598
17600
17602
17604
17606
17608
17610
17612
17614
17616
17618
17620
17622
17624
17626
17628
17630
17632
17634
17636
17638
17640
17642
17644
17646
17648
17650
17652
17654
17656
17658
17660
17662
17664
17666
17668
17670
17672
17674
17676
17678
17680
17682
17684
17686
17688
17690
17692
17694
17696
17698
17700
17702
17704
17706
17708
17710
17712
17714
17716
17718
17720
17722
17724
17726
17728
17730
17732
17734
17736
17738
17740
17742
17744
17746
17748
17750
17752
17754
17756
17758
17760
17762
17764
17766
17768
17770
17772
17774
17776
17778
17780
17782
17784
17786
17788
17790
17792
17794
17796
17798
17800
17802
17804
17806
17808
17810
17812
17814
17816
17818
17820
17822
17824
17826
17828
17830
17832
17834
17836
17838
17840
17842
17844
17846
17848
17850
17852
17854
17856
17858
17860
17862
17864
17866
17868
17870
17872
17874
17876
17878
17880
17882
17884
1788

20792
20794
20796
20798
20800
20802
20804
20806
20808
20810
20812
20814
20816
20818
20820
20822
20824
20826
20828
20830
20832
20834
20836
20838
20840
20842
20844
20846
20848
20850
20852
20854
20856
20858
20860
20862
20864
20866
20868
20870
20872
20874
20876
20878
20880
20882
20884
20886
20888
20890
20892
20894
20896
20898
20900
20902
20904
20906
20908
20910
20912
20914
20916
20918
20920
20922
20924
20926
20928
20930
20932
20934
20936
20938
20940
20942
20944
20946
20948
20950
20952
20954
20956
20958
20960
20962
20964
20966
20968
20970
20972
20974
20976
20978
20980
20982
20984
20986
20988
20990
20992
20994
20996
20998
21000
21002
21004
21006
21008
21010
21012
21014
21016
21018
21020
21022
21024
21026
21028
21030
21032
21034
21036
21038
21040
21042
21044
21046
21048
21050
21052
21054
21056
21058
21060
21062
21064
21066
21068
21070
21072
21074
21076
21078
21080
21082
21084
21086
21088
21090
21092
21094
21096
21098
21100
21102
21104
21106
21108
21110
21112
21114
21116
21118
21120
21122
2112

24082
24084
24086
24088
24090
24092
24094
24096
24098
24100
24102
24104
24106
24108
24110
24112
24114
24116
24118
24120
24122
24124
24126
24128
24130
24132
24134
24136
24138
24140
24142
24144
24146
24148
24150
24152
24154
24156
24158
24160
24162
24164
24166
24168
24170
24172
24174
24176
24178
24180
24182
24184
24186
24188
24190
24192
24194
24196
24198
24200
24202
24204
24206
24208
24210
24212
24214
24216
24218
24220
24222
24224
24226
24228
24230
24232
24234
24236
24238
24240
24242
24244
24246
24248
24250
24252
24254
24256
24258
24260
24262
24264
24266
24268
24270
24272
24274
24276
24278
24280
24282
24284
24286
24288
24290
24292
24294
24296
24298
24300
24302
24304
24306
24308
24310
24312
24314
24316
24318
24320
24322
24324
24326
24328
24330
24332
24334
24336
24338
24340
24342
24344
24346
24348
24350
24352
24354
24356
24358
24360
24362
24364
24366
24368
24370
24372
24374
24376
24378
24380
24382
24384
24386
24388
24390
24392
24394
24396
24398
24400
24402
24404
24406
24408
24410
24412
2441

27356
27358
27360
27362
27364
27366
27368
27370
27372
27374
27376
27378
27380
27382
27384
27386
27388
27390
27392
27394
27396
27398
27400
27402
27404
27406
27408
27410
27412
27414
27416
27418
27420
27422
27424
27426
27428
27430
27432
27434
27436
27438
27440
27442
27444
27446
27448
27450
27452
27454
27456
27458
27460
27462
27464
27466
27468
27470
27472
27474
27476
27478
27480
27482
27484
27486
27488
27490
27492
27494
27496
27498
27500
27502
27504
27506
27508
27510
27512
27514
27516
27518
27520
27522
27524
27526
27528
27530
27532
27534
27536
27538
27540
27542
27544
27546
27548
27550
27552
27554
27556
27558
27560
27562
27564
27566
27568
27570
27572
27574
27576
27578
27580
27582
27584
27586
27588
27590
27592
27594
27596
27598
27600
27602
27604
27606
27608
27610
27612
27614
27616
27618
27620
27622
27624
27626
27628
27630
27632
27634
27636
27638
27640
27642
27644
27646
27648
27650
27652
27654
27656
27658
27660
27662
27664
27666
27668
27670
27672
27674
27676
27678
27680
27682
27684
27686
2768

In [160]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
print(np.all(a==b)) # 전체가 참일 때 참
print(np.any(a==b)) # 하나라도 참이면 참
print(np.exp(a)) # 지수함수(자연대수 : 2.718)

False
True
[ 2.71828183  7.3890561  20.08553692 54.59815003]


# 선형대수 : 선형으로 해결하자. => 비선형도 잘게 나누면 선형

# 행렬의 종류
- 정방행렬 : 정사각형, 행수와 열수가 같다.ex)공분산행렬, 상관행렬
- 대칭행렬 : 우상단과 좌하단 같은것
- 대각행렬 : scale을 변화시키는 요소
- 단위행렬(identity) : 행렬곱의 항등원, 행렬과 역행렬을 곱하면 단위행렬
- 역행렬 : 행렬의 나눗셈을 위해 구해서 곱해지는 행렬(정방행렬만 가능)
- 특이행렬 : 역행렬이 없는 행렬
- 직교행렬 : 축의 정직교, 각축간의 내적이 0인 행렬
- 정방행렬이면서 대칭행렬 : 공분산행렬, 상관계수행렬, 거리행렬
- 공분산 : 두 수간의 관계 ((한 수-평균) * (다른 수 - 평균))/(n-1)
- 상관계수(표준화 -1~1) : 공분산/표준편차의 곱

In [161]:
import numpy as np
F1 = np.array([[1,2], [3,4]])
F2 = np.array([[2,2], [2,2]])
print(F1)
print(F2)
print(F1+F2) # 요소끼리
print(F1*F2)
print(F1@F2) #행렬곱도 내적, 두 벡터의 사이각을 구함
# 1,2    2,2,1
# 3,4    2,2,1    차원확장

[[1 2]
 [3 4]]
[[2 2]
 [2 2]]
[[3 4]
 [5 6]]
[[2 4]
 [6 8]]
[[ 6  6]
 [14 14]]


In [ ]:
# 방정식의 해
 2x1 + x2 -2x3 = -3
 3x1 +      x3 = 5
  x1 + x2 - x3 = -2

In [164]:
A = np.array([[2,1,-2], [3,0,1], [1,1,-1]])
print(A)
b = np.transpose(np.array([[-3,5,-2]])) # 열로 전치
print(b)
x = np.linalg.solve(A,b) # A의 역행렬을 구해서 b와 곱해줌
print(x)

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
[[-3]
 [ 5]
 [-2]]
[[ 1.]
 [-1.]
 [ 2.]]


In [165]:
np.dot(np.linalg.inv(A),b) # 행렬곱

array([[ 1.],
       [-1.],
       [ 2.]])

In [166]:
np.linalg.inv(A)@b # 왜 역행렬을 구해야 하는가? 행렬은 나눗셈이 없어서 역행렬를 곱해서 구한다.

array([[ 1.],
       [-1.],
       [ 2.]])

In [167]:
2*1 + (-1) -2*2

-3

In [168]:
a = np.array([0,1,0]) # y축
b = np.array([1,0,0]) # x축
res = np.dot(a,b) # 내적 사이각 = 직각
print(res)

0


In [171]:
print(np.linalg.norm(a)) # 벡터의 크기
print(np.linalg.norm(b))
print(np.linalg.norm(a) * np.linalg.norm(b))
rad = res/(np.linalg.norm(a) * np.linalg.norm(b))
print("cos theta", rad)
print(np.arccos(rad)) # theta 값을 구함
print(np.degrees(np.arccos(rad))) # 사람이 알아보는 각도로 표현

1.0
1.0
1.0
cos theta 0.0
1.5707963267948966
90.0


In [172]:
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)
print(x)
print(y)
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [ ]:
# 다음 방정식의 해를 구하고 검산하시요

-x + y + z = 6
-2y +5z = -4
-2x + 5y -z = 27

In [177]:
a = np.array([[1, 1, 1], [0,2, 5], [2,5,-1]])
print(a)
b = np.transpose(np.array([[6, -4, 27]]))
print(b)
x = np.linalg.solve(a,b)
print(x)

[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
[[ 6]
 [-4]
 [27]]
[[ 5.]
 [ 3.]
 [-2.]]


In [178]:
print(5*1 + 3*1  -2*1)
print(3 * 2 -2*5)
print(5 * 2 +3 *5  -2*-1)

6
-4
27
